name: Test
on: [push, pull_request]
jobs:
  CypressMockTests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install Node.js packages for Cypress
        run: npm install
        
      Get-Test-Groups:
    runs-on: ubuntu-latest
    outputs:
      test-groups: ${{ steps.set-groups.outputs.test-groups }}
    steps:
      - uses: actions/checkout@v4
      - id: set-groups
        shell: bash
        run: |
          set -x  # Enable debug mode to see each command
          
          echo "Checking directory structure..."
          ls -la frontend/src/__tests__/cypress/cypress/tests/ || echo "Base test directory not found"
          
          if [ -d "frontend/src/__tests__/cypress/cypress/tests/mocked" ]; then
            echo "Found mocked tests directory"
            
            # Get directories and create JSON array - force compact output with -c
            DIRS=$(cd frontend/src/__tests__/cypress/cypress/tests/mocked && \
                  find . -maxdepth 1 -mindepth 1 -type d -printf "%f\n" | \
                  jq -R . | jq -c -s .)
            
            # Output in the correct format for GitHub Actions
            echo "test-groups=$DIRS" >> "$GITHUB_OUTPUT"
            
            echo "Generated test groups:"
            cat "$GITHUB_OUTPUT"
          else
            echo "No mocked tests directory found, using default"
            echo "test-groups=[\"default\"]" >> "$GITHUB_OUTPUT"
          fi

  Cypress-Tests:
    needs: [Setup, Get-Test-Groups]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test-group: ${{ fromJson(needs.Get-Test-Groups.outputs.test-groups) }}
    steps:
      - uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/Cypress
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/backend/node_modules
            ${{ github.workspace }}/frontend/node_modules
          key: ${{ runner.os }}-18.x-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Run Cypress tests
        run: |
          if [ "${{ matrix.test-group }}" == "default" ]; then
            npm run test:cypress-ci
          else
            npm run test:cypress-ci -- --spec "src/__tests__/cypress/cypress/tests/mocked/${{ matrix.test-group }}/**/*"
          fi
        working-directory: ./frontend